import { Flag } from '../../types/general';

export const UNIT_FLAGS: Flag[] = [
  { bit: 0,  name: 'UNK_0 -Movement checks disabled, likely paired with loss of client control packet.' },
  { bit: 1,  name: 'NON_ATTACKABLE' },
  { bit: 2,  name: 'CLIENT_CONTROL_LOST - Generic unspecified loss of control initiated by server script, movement checks disabled, paired with loss of client control packet.' },
  { bit: 3,  name: 'PLAYER_CONTROLLED - players, pets, totems, guardians, companions, charms, any units associated with players' },
  { bit: 4,  name: 'RENAME' },
  { bit: 5,  name: 'PREPARATION - don\'t take reagents for spells with SPELL_ATTR5_NO_REAGENT_WHILE_PREP' },
  { bit: 6,  name: 'UNK_6 - not sure what it does, but it is needed to cast nontriggered spells in smart_scripts - Related to Movement? often paired with UNIT_FLAG_SWIMMING' },
  { bit: 7,  name: 'NOT_ATTACKABLE_1 - UNIT_FLAG_PVP + UNIT_FLAG_NOT_ATTACKABLE_1 = UNIT_FLAG_NON_PVP_ATTACKABLE – blue color target' },
  { bit: 8,  name: 'IMMUNE_TO_PLAYER - disables combat/assistance with PlayerCharacters (PC) - Target is immune to players' },
  { bit: 9,  name: 'IMMUNE_TO_NPC - disables combat/assistance with NonPlayerCharacters (NPC) - makes you unable to attack everything. Almost identical to our “civilian”-term. Will ignore it’s surroundings and not engage in combat unless “called upon” or engaged by another unit.' },
  { bit: 10, name: 'LOOTING - loot animation' },
  { bit: 11, name: 'PET_IN_COMBAT - in combat?, 2.0.8' },
  { bit: 12, name: 'PVP - Allows item spells to be casted upon. changed in 3.0.3' },
  { bit: 13, name: 'SILENCED - Can’t cast spells' },
  { bit: 14, name: 'PERSUADED' },
  { bit: 15, name: 'SWIMMING - Only Swim ' },
  { bit: 16, name: 'NON_ATTACKABLE_2 - removes attackable icon, if on yourself, cannot assist self but can cast TARGET_SELF spells – added by SPELL_AURA_MOD_UNATTACKABLE' },
  { bit: 17, name: 'PACIFIED - Creature will not attack' },
  { bit: 18, name: 'STUNNED' },
  { bit: 19, name: 'IN_COMBAT' },
  { bit: 20, name: 'TAXI_FLIGHT - disable casting at client side spell not allowed by taxi flight - Unit is on taxi, paired with a duplicate loss of client control packet (likely a legacy serverside hack)' },
  { bit: 21, name: 'DISARMED - disable melee spells casting - ...\'Required melee weapon\' added to melee spells tooltip.' },
  { bit: 22, name: 'CONFUSED - Unit is a subject to confused movement, movement checks disabled, paired with loss of client control packet.' },
  { bit: 23, name: 'FLEEING - feared - Unit is a subject to fleeing movement, movement checks disabled, paired with loss of client control packet.' },
  { bit: 24, name: 'POSSESSED/PLAYER_CONTROLLED - used in spell Eyes of the Beast for pet - Unit is under remote control by another unit2' },
  { bit: 25, name: 'NOT_SELECTABLE - Can’t be selected by mouse or with /target {name} command.' },
  { bit: 26, name: 'SKINNABLE' },
  { bit: 27, name: 'MOUNT - The client seems to handle it perfectly. Also used when making custom mounts.' },
  { bit: 28, name: 'UNK_28 - PreventKneelingWhenLooting' },
  { bit: 29, name: 'UNK_29 - Used in Feign Death spell or NPC will play dead' },
  { bit: 30, name: 'SHEATHE' },
  { bit: 31, name: 'UNK_31 - set skinnable icon and also changes color of portrait)(no affect in 2.4.3)' },
];
